### ISSUE TITLE
fix error in file upload

### ISSUE THREAD

**Issue by mettiu** [mettiu/scatter-client#9]
If you try to upload file by issuing an ```upload``` command, you ger this error:

```
http://localhost:3000:~$ upload test_data/img.jpeg /
file: test_data/img.jpeg
TypeError: Cannot read property 'chunkUpload' of undefined
    at getChunkSplitInfo (/home/mettiu/WebstormProjects/scatter-client/commands/fileUpload.js:8:33)
    at uploadFile (/home/mettiu/WebstormProjects/scatter-client/commands/fileUpload.js:55:21)
    at CommandInstance.<anonymous> (/home/mettiu/WebstormProjects/scatter-client/zot.js:132:11)
    at Session.session.execCommandSet (/home/mettiu/WebstormProjects/scatter-client/node_modules/vorpal/dist/session.js:470:20)
    at Vorpal.vorpal._exec (/home/mettiu/WebstormProjects/scatter-client/node_modules/vorpal/dist/vorpal.js:960:18)
    at Vorpal.vorpal._execQueueItem (/home/mettiu/WebstormProjects/scatter-client/node_modules/vorpal/dist/vorpal.js:751:17)
    at Vorpal.vorpal._queueHandler (/home/mettiu/WebstormProjects/scatter-client/node_modules/vorpal/dist/vorpal.js:735:10)
    at Vorpal.vorpal.exec (/home/mettiu/WebstormProjects/scatter-client/node_modules/vorpal/dist/vorpal.js:682:10)
    at /home/mettiu/WebstormProjects/scatter-client/node_modules/vorpal/dist/vorpal.js:625:10
    at module.exports.completed (/home/mettiu/WebstormProjects/scatter-client/node_modules/vorpal/dist/ui.js:220:13)
```

The problem is with config data, which war refactored.

**Comment by mettiu** [comment]
Fixed by correcting config variable reference. Improved ```getChunkSplitInfo``` function by using an arrow function.
